name       : python-sphinx
version    : 1.6.3
release    : 4
source     :
    - https://github.com/sphinx-doc/sphinx/archive/1.6.3.tar.gz : 0707b2a8a47462c06b0107426b8512a68332232241e414384b6b86cce9b7f60f
license    : BSD-2-Clause
component  : programming.python
summary    : Python documentation generator
description: |
    Python documentation generator
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - alabaster
    - pygments
    - python-babel
    - python-docutils
    - python-imagesize
    - python-jinja
    - python-nose
    - python-requests
    - python-setuptools
    - python-six
    - python-snowballstemmer
    - python-sphinxcontrib-websupport
    - python-typing
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    # fix python 2/3 conflict
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}3"
    done
    %python_install
