name       : python-sphinx
version    : 5.3.0
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/S/Sphinx/Sphinx-5.3.0.tar.gz : 51026de0a9ff9fc13c05d74913ad66047e104f56a129ff73e174eb5c3ee794b5
homepage   : https://www.sphinx-doc.org
license    : BSD-2-Clause
component  : programming.python
summary    : Python documentation generator
description: |
    Python documentation generator
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
rundeps    :
    - alabaster
    - pygments
    - python-docutils
    - python-imagesize
    - python-importlib-metadata
    - python-jinja
    - python-nose
    - python-packaging
    - python-requests
    - python-six
    - python-snowballstemmer
    - python-sphinxcontrib-applehelp
    - python-sphinxcontrib-devhelp
    - python-sphinxcontrib-htmlhelp
    - python-sphinxcontrib-jsmath
    - python-sphinxcontrib-qthelp
    - python-sphinxcontrib-serializinghtml
    - python-sphinxcontrib-websupport
build      : |
    %python3_setup
install    : |
    %python3_install
