name       : python-sphinx
version    : 4.5.0
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/S/Sphinx/Sphinx-4.5.0.tar.gz : 7bf8ca9637a4ee15af412d1a1d9689fec70523a68ca9bb9127c2f3eeb344e2e6
homepage   : https://www.sphinx-doc.org
license    : BSD-2-Clause
component  : programming.python
summary    : Python documentation generator
description: |
    Python documentation generator
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - alabaster
    - python-docutils
    - python-imagesize
    - python-importlib-metadata
    - python-jinja
    - python-nose
    - python-packaging
    - python-requests
    - python-six
    - python-snowballstemmer
    - python-sphinxcontrib-applehelp
    - python-sphinxcontrib-devhelp
    - python-sphinxcontrib-htmlhelp
    - python-sphinxcontrib-jsmath
    - python-sphinxcontrib-qthelp
    - python-sphinxcontrib-serializinghtml
    - python-sphinxcontrib-websupport
build      : |
    %python3_setup
install    : |
    %python3_install
