name       : python-sphinx
version    : 1.4.4
release    : 3
source     :
    - https://pypi.python.org/packages/20/a2/72f44c84f6c4115e3fef58d36d657ec311d80196eab9fd5ec7bcde76143b/Sphinx-1.4.4.tar.gz : 3effd6373734bd59f7457fed2f0bd4ba7ec3c70b4598d7c2e5193a42209dbfa0
license    : BSD-2-Clause
component  : programming.python
summary    : Python documentation generator
description: |
    Python documentation generator
builddeps  :
    - pkgconfig(python-2.7)
    - alabaster
    - python-babel
    - python-docutils
    - python-imagesize
    - python-jinja
    - python-nose
    - python-setuptools
    - python-six
    - python-snowballstemmer
rundeps    :
    - alabaster
    - pygments
    - python-babel
    - python-docutils
    - python-imagesize
    - python-jinja
    - python-nose
    - python-setuptools
    - python-six
    - python-snowballstemmer
build      : |
    %python_setup
install    : |
    %python_install
