name       : python-sphinx
version    : 3.5.1
release    : 10
source     :
    - https://github.com/sphinx-doc/sphinx/archive/v3.5.1.tar.gz : 888dece1245c0239085797f649bda9909e8276a68d9aa5ac5560785fcb4a3696
license    : BSD-2-Clause
component  : programming.python
summary    : Python documentation generator
description: |
    Python documentation generator
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - alabaster
    - pygments
    - python-babel
    - python-docutils
    - python-imagesize
    - python-jinja
    - python-nose
    - python-packaging
    - python-requests
    - python-setuptools
    - python-six
    - python-snowballstemmer
    - python-sphinxcontrib-applehelp
    - python-sphinxcontrib-devhelp
    - python-sphinxcontrib-htmlhelp
    - python-sphinxcontrib-jsmath
    - python-sphinxcontrib-qthelp
    - python-sphinxcontrib-serializinghtml
    - python-sphinxcontrib-websupport
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test py.test3
