name       : python-sphinx
version    : 1.7.5
release    : 6
source     :
    - https://github.com/sphinx-doc/sphinx/archive/v1.7.5.tar.gz : 2e93f4330dc44fc07d31e0de5d4f81e9281a78739208792fd08619b65c81c853
license    : BSD-2-Clause
component  : programming.python
summary    : Python documentation generator
description: |
    Python documentation generator
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - alabaster
    - pygments
    - python-babel
    - python-docutils
    - python-imagesize
    - python-jinja
    - python-nose
    - python-requests
    - python-setuptools
    - python-six
    - python-snowballstemmer
    - python-sphinxcontrib-websupport
    - python-typing
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    # Append py3 binaries with 3
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}3"
    done
    %python_install
