name       : python-sphinx
version    : 4.5.0
release    : 12
source     :
    - https://github.com/sphinx-doc/sphinx/archive/refs/tags/v4.5.0.tar.gz : 4d040bed5b304d2c2f69a12bdcc42428ff519f138f59b5108ebb70aaf15f1707
license    : BSD-2-Clause
component  : programming.python
summary    : Python documentation generator
description: |
    Python documentation generator
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - alabaster
    - pygments
    - python-babel
    - python-docutils
    - python-imagesize
    - python-jinja
    - python-nose
    - python-packaging
    - python-requests
    - python-setuptools
    - python-six
    - python-snowballstemmer
    - python-sphinxcontrib-applehelp
    - python-sphinxcontrib-devhelp
    - python-sphinxcontrib-htmlhelp
    - python-sphinxcontrib-jsmath
    - python-sphinxcontrib-qthelp
    - python-sphinxcontrib-serializinghtml
    - python-sphinxcontrib-websupport
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test py.test3
